-- bootstrap lazy.nvim, LazyVim and your plugins

require("config.lazy")
vim.cmd([[colorscheme dracula]])

-- local lspconf = require("lspconfig")
--
-- lspconf.lua_ls.setup({
--   settings = {
--     Lua = {
--       hint = {
--         enable = true,
--       },
--     },
--   },
-- })
--
-- lspconf.tsserver.setup({
--   settings = {
--     javascript = {
--       inlayHints = {
--         includeInlayEnumMemberValueHints = true,
--         includeInlayFunctionLikeReturnTypeHints = true,
--         includeInlayFunctionParameterTypeHints = true,
--         includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
--         includeInlayParameterNameHintsWhenArgumentMatchesName = true,
--         includeInlayPropertyDeclarationTypeHints = true,
--         includeInlayVariableTypeHints = false,
--       },
--     },
--
--     typescript = {
--       inlayHints = {
--         includeInlayEnumMemberValueHints = true,
--         includeInlayFunctionLikeReturnTypeHints = true,
--         includeInlayFunctionParameterTypeHints = true,
--         includeInlayParameterNameHints = "all", -- 'none' | 'literals' | 'all';
--         includeInlayParameterNameHintsWhenArgumentMatchesName = true,
--         includeInlayPropertyDeclarationTypeHints = true,
--         includeInlayVariableTypeHints = false,
--       },
--     },
--   },
-- })
